### PR TITLE
Upgrade cordova plugin image & fix permission :bug: on Android

### PR DESCRIPTION
**Pull request by kosssi**
- [x] Upgrade plugin from 1.2.2 to 2.0.3
- [x] Add specific authorization to fix bug on Android ([doc](https://github.com/terikon/cordova-plugin-photo-library#permissions))
- [x] Add a filter on Android

To valide: On settings clic on 'Launch Backup' you can see an Android popup with authorization.

### CODE REVIEW

**Comment by enguerran** [comment]
Could you ask a description to explain how this PR should be approve or not?

**Comment by kosssi** [comment]
@enguerran done

**Comment by enguerran** [comment]
Oh wait!

It seems that the metadata were added to cozy-stack (but not the binary files).
And I test it on Android 5.1.1, so no permission popup.

And if I check the permissions registered in the app info, I can see:

> modify or delete the contents of your USB storage
> read the contents of your USB storage

**Comment by enguerran** [comment]
Not related but I have to share this:

videotogif_2017 03 02_08 51 43

On this gif, what do we see:

1. I open the application on my Android phone
1. I create a folder named "Mon dossier" (french for "My folder")
1. I *enter* the folder
1. I refresh as asked
1. I go back in the root folder
1. I refresh as asked
1. No folder is displayed...

... but when I look into the app.cozy.local:8080/#/files app, it's there!

screenshot at 08-55-18

**Comment by enguerran** [comment]
@kosssi What do you want to do with this?

**Comment by kosssi** [comment]
Finally I update to 2.0.3, I upload from my Nexus & from ios emulator.

capture d ecran 2017-03-07 a 09 40 00

capture d ecran 2017-03-07 a 09 40 20

**Comment by enguerran** [comment]
Error spotted above are note related to this Pull Request, but it is related to this bug https://github.com/cozy/cozy-client-js/issues/106

**Pull request merged**
