### PR TITLE
Improve component replacement in Bar

### PR DESCRIPTION
**Pull request by m4dz**
This PR is related to https://github.com/cozy/cozy-bar/pull/28 as it uses its new mechanism to disable title in cozy-bar and allow custom component replacement. It also adjust some alignments.

### CODE REVIEW

**Comment by y-lohse** [comment]
Thanks @m4dz ! Code is good and everything works as expected. Even the annoying z-index bug :-)

However, if we merge this PR as it is, files is going to be broken. Correct me if I'm wrong, but we need to wait for https://github.com/cozy/cozy-bar/pull/28 to be merged and a new version of the bar to be released. Do you mind waiting for that and adding the dependency upgrade to this PR once we're so far?

@enguerran : FYI, this PR also fixes the double title bug on mobile standalone.

**Comment by m4dz** [comment]
@y-lohse 

> Do you mind waiting for that and adding the dependency upgrade to this PR once we're so far?

Of course yes :+1: 

Thanks for pinging @enguerran too, I forgot (my bad, I'm sorry :disappointed:)

**Comment by m4dz** [comment]
Deps are now updated, in waiting for https://github.com/cozy/cozy-stack/pull/399

**Comment by m4dz** [comment]
Wooohoooo \o/ ! READY TO RUUUUUUMBLE !

@y-lohse, it's when you want now :gift:

**Comment by y-lohse** [comment]
Wonderful, thank you 👍

**Pull request merged**
