### PR TITLE
Update cozy-ui to beta12

### PR DESCRIPTION
**Pull request by CPatchane**

### CODE REVIEW

**Comment by y-lohse** [comment]
So, thanks for the PR, but I'm not too comfortable merging it right now. As much as it helps us, it will also break a few things in the UI and that might annoy other people.

If you don't mind, we can leave it un-merged and wait for @GoOz 's PR that should fix *everything* (no pressure). In the meantime, we can merge this branch into our local working branches to have these changes.

@GoOz what do you think? Do you have a rough ETA for the other PR?
@kosssi & @enguerran : On a scale from 1 to fuck-dont-merge-this, where do you guys stand?

**Comment by CPatchane** [comment]
@y-lohse I agree, let's do like this. 👍

**Comment by GoOz** [comment]
Honestly those are minor changes, nothing Git can't handle and even if it doesn't, conflicts won't be hard to fix.
The thing is I don't expect to submit any PR before tomorrow afternoon, so… if you really need to keep going on your tasks and can't afford the wait, do it, merge this PR. I'll rebase it myself afterwards and take care of the potential conflicts. :)

**Comment by enguerran** [comment]
No side effect spotted in this PR, so I suggest to merge it.

By the way @CPatchane and @y-lohse: prefixing the PR with a [WIP] is clearer for a merge stand by than the *changes requested* status as the big green *merge pull request* button is gray while the [WIP] is there.

screenshot at 19-06-03

**Pull request closed without merging**
