### PR TITLE
[fix] Fil 16 fixes

### PR DESCRIPTION
**Pull request by y-lohse**
Fixes some minor issues:

- modal close button and mobile view
- a visual regression affecting checkboxes
- simplified translations
- better notifications

### CODE REVIEW

**Comment by y-lohse** [comment]
I agree that the names should be the same. However, I was more inclined to eventually  rename "Alerters" as "Notifications" as I feel it's a more accurate description of what it does. But you confirm it's a conscious choice that has already been discussed, I'm happy to rename the few instances of "notifications".

**Comment by enguerran** [comment]
Did you see @kosssi add a modal component in cozy-ui? (see https://github.com/cozy/cozy-ui/pull/53)

**Comment by y-lohse** [comment]
Yes, I think it will make sense to use that modal eventually. But that implies another cozy-ui update first, so I'd like to land FIL-16 before. It's been in the works for way too long already.

**Comment by gregorylegarec** [comment]
@y-lohse Yep we already discussed about the naming of notifications/alerts, we concluded that notification was a more complex model, (they can be for example stacked and "waiting" for consultation), as the alert was more the UI aspect of it. By the way, the opinions in the team were divided, so if this naming confuse too much developers and contributors, we may discuss to change it again in the future.

**Comment by gregorylegarec** [comment]
Great job @y-lohse !

**Pull request merged**
